title: "Joe's Blog"
author: "Joe Koop"
description: "This is my blog. I don't know what I'm doing."

#theme: "minima"
remote_theme: jekyll/minima
minima:
  skin: auto

rss: rss

markdown: GFM

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: untagged
